services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Wacon\Mctest\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Wacon\Mctest\Domain\Riddler\Riddler:
    public: true
